name: flutter_application_try_0
description: AJ Fitness Gym - Client Attendance & Goal Tracking System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Enhancements
  iconsax: ^0.0.8
  google_fonts: ^6.1.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  
  # Database
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true